import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Task, TaskStatus } from '@nexus-queue/shared-models';
import { TaskEntity } from '../entities';

/**
 * Unified task lifecycle store backed by TypeORM.
 * Replaces the in-memory Map with a persistent repository.
 */
@Injectable()
export class TaskStoreService {
  private readonly logger = new Logger(TaskStoreService.name);

  constructor(
    @InjectRepository(TaskEntity)
    private readonly taskRepo: Repository<TaskEntity>
  ) {}

  /** Generate a unique task ID (UUID from the DB will be used for new tasks) */
  generateTaskId(): string {
    // UUIDs are generated by TypeORM on save; this returns a placeholder
    // that gets replaced when create() persists the task.
    // Callers that need the real ID must use the returned task from create().
    return `TASK-${Date.now()}-${Math.random().toString(36).substr(2, 6)}`;
  }

  /** Store a new task */
  async create(task: Task): Promise<Task> {
    const entity = this.toEntity(task);
    const saved = await this.taskRepo.save(entity);
    this.logger.debug(`Task created: ${saved.id} (status: ${saved.status})`);
    return this.toModel(saved);
  }

  /** Get a task by ID */
  async getById(taskId: string): Promise<Task | undefined> {
    const entity = await this.taskRepo.findOneBy({ id: taskId });
    return entity ? this.toModel(entity) : undefined;
  }

  /** Get a task by external ID */
  async getByExternalId(externalId: string): Promise<Task | undefined> {
    const entity = await this.taskRepo.findOneBy({ externalId });
    return entity ? this.toModel(entity) : undefined;
  }

  /** Check if an external ID already exists */
  async hasExternalId(externalId: string): Promise<boolean> {
    const count = await this.taskRepo.count({ where: { externalId } });
    return count > 0;
  }

  /**
   * Transition a task to a new status with updated fields.
   * Returns the updated task or undefined if not found.
   */
  async updateStatus(
    taskId: string,
    status: TaskStatus,
    updates?: Partial<Task>
  ): Promise<Task | undefined> {
    const entity = await this.taskRepo.findOneBy({ id: taskId });
    if (!entity) {
      this.logger.warn(`Task not found for status update: ${taskId}`);
      return undefined;
    }

    const oldStatus = entity.status;
    const merged = this.mergeUpdates(entity, { ...updates, status });
    const saved = await this.taskRepo.save(merged);

    this.logger.debug(`Task ${taskId} status: ${oldStatus} → ${status}`);
    return this.toModel(saved);
  }

  /** Update arbitrary task fields without changing status */
  async update(taskId: string, updates: Partial<Task>): Promise<Task | undefined> {
    const entity = await this.taskRepo.findOneBy({ id: taskId });
    if (!entity) return undefined;

    const merged = this.mergeUpdates(entity, updates);
    const saved = await this.taskRepo.save(merged);
    return this.toModel(saved);
  }

  /** Get all tasks with a given status */
  async getByStatus(status: TaskStatus): Promise<Task[]> {
    const entities = await this.taskRepo.findBy({ status });
    return entities.map((e) => this.toModel(e));
  }

  /** Get all tasks assigned to an agent */
  async getByAgent(agentId: string): Promise<Task[]> {
    const entities = await this.taskRepo.findBy({ assignedTo: agentId });
    return entities.map((e) => this.toModel(e));
  }

  /** Get counts by status for monitoring */
  async getStatusCounts(): Promise<Record<string, number>> {
    const results = await this.taskRepo
      .createQueryBuilder('task')
      .select('task.status', 'status')
      .addSelect('COUNT(*)', 'count')
      .groupBy('task.status')
      .getRawMany();

    const counts: Record<string, number> = {};
    for (const row of results) {
      counts[row['status']] = parseInt(row['count'], 10);
    }
    return counts;
  }

  /** Total tasks in store */
  async getSize(): Promise<number> {
    return this.taskRepo.count();
  }

  // === Private mapping helpers ===

  private toEntity(task: Task): TaskEntity {
    const entity = new TaskEntity();
    entity.id = task.id;
    entity.externalId = task.externalId;
    entity.pipelineId = task.metadata?.['_pipelineId'];
    entity.queueId = task.queueId;
    entity.workType = task.workType;
    entity.title = task.title;
    entity.description = task.description;
    entity.payloadUrl = task.payloadUrl;
    entity.displayMode = task.displayMode;
    entity.priority = task.priority;
    entity.skills = task.skills;
    entity.queueName = task.queue;
    entity.status = task.status;
    entity.payload = task.metadata;
    entity.assignedTo = task.assignedAgentId;
    entity.retryCount = 0;
    entity.maxRetries = 3;
    entity.reservationTimeout = task.reservationTimeout;
    entity.reservedAt = task.reservedAt ? new Date(task.reservedAt) : undefined;
    entity.completedAt = task.completedAt ? new Date(task.completedAt) : undefined;
    entity.enqueuedAt = task.createdAt ? new Date(task.createdAt) : new Date();
    entity.actions = task.actions as unknown as Record<string, unknown>[];
    entity.assignmentHistory = task.assignmentHistory as unknown as Record<string, unknown>[];
    entity.disposition = task.disposition as unknown as Record<string, unknown>;
    return entity;
  }

  private toModel(entity: TaskEntity): Task {
    return {
      id: entity.id,
      externalId: entity.externalId,
      workType: entity.workType,
      title: entity.title,
      description: entity.description,
      payloadUrl: entity.payloadUrl || '',
      displayMode: entity.displayMode as Task['displayMode'],
      metadata: entity.payload,
      priority: entity.priority,
      skills: entity.skills,
      queueId: entity.queueId,
      queue: entity.queueName,
      status: entity.status as TaskStatus,
      createdAt: entity.createdAt?.toISOString() || new Date().toISOString(),
      availableAt: entity.enqueuedAt?.toISOString(),
      reservedAt: entity.reservedAt?.toISOString(),
      completedAt: entity.completedAt?.toISOString(),
      assignedAgentId: entity.assignedTo,
      reservationTimeout: entity.reservationTimeout,
      actions: entity.actions as unknown as Task['actions'],
      assignmentHistory: entity.assignmentHistory as unknown as Task['assignmentHistory'],
      disposition: entity.disposition as unknown as Task['disposition'],
    };
  }

  private mergeUpdates(entity: TaskEntity, updates: Partial<Task>): TaskEntity {
    if (updates.status !== undefined) entity.status = updates.status;
    if (updates.assignedAgentId !== undefined) entity.assignedTo = updates.assignedAgentId;
    if (updates.queueId !== undefined) entity.queueId = updates.queueId;
    if (updates.metadata !== undefined) entity.payload = updates.metadata;
    if (updates.reservedAt !== undefined) entity.reservedAt = updates.reservedAt ? new Date(updates.reservedAt) : undefined;
    if (updates.completedAt !== undefined) entity.completedAt = updates.completedAt ? new Date(updates.completedAt) : undefined;
    if (updates.priority !== undefined) entity.priority = updates.priority;
    if (updates.disposition !== undefined) entity.disposition = updates.disposition as unknown as Record<string, unknown>;
    if (updates.assignmentHistory !== undefined) entity.assignmentHistory = updates.assignmentHistory as unknown as Record<string, unknown>[];
    return entity;
  }
}
