/**
 * Default seed data constants for the Nexus Queue system.
 * Used by seed.ts to populate the database with initial reference data.
 */

export const DEFAULT_DISPOSITIONS = [
  {
    id: 'disp-resolved',
    code: 'RESOLVED',
    name: 'Resolved',
    description: 'Issue fully resolved in this interaction',
    category: 'resolved',
    requiresNote: false,
    active: true,
    order: 1,
    icon: 'check_circle',
    color: 'green',
    queueIds: [],
    workTypeIds: [],
  },
  {
    id: 'disp-transferred',
    code: 'TRANSFERRED',
    name: 'Transferred',
    description: 'Transferred to another team or department',
    category: 'transferred',
    requiresNote: false,
    active: true,
    order: 2,
    icon: 'swap_horiz',
    color: 'blue',
    queueIds: [],
    workTypeIds: [],
  },
  {
    id: 'disp-unresolved',
    code: 'UNRESOLVED',
    name: 'Unresolved',
    description: 'Issue could not be resolved',
    category: 'unresolved',
    requiresNote: true,
    active: true,
    order: 3,
    icon: 'cancel',
    color: 'red',
    queueIds: [],
    workTypeIds: [],
  },
  {
    id: 'disp-callback',
    code: 'CALLBACK_SCHEDULED',
    name: 'Callback Scheduled',
    description: 'Follow-up callback scheduled for later',
    category: 'callback',
    requiresNote: false,
    active: true,
    order: 4,
    icon: 'schedule_send',
    color: 'orange',
    queueIds: [],
    workTypeIds: [],
  },
];

export const DEFAULT_WORK_STATES = [
  {
    id: 'ws-available',
    state: 'AVAILABLE',
    label: 'Available',
    description: 'Agent is available to receive tasks',
    allowsWork: true,
    maxDuration: null,
    requiresReason: false,
    createdBy: 'system',
  },
  {
    id: 'ws-break',
    state: 'BREAK',
    label: 'Break',
    description: 'Agent is on a scheduled break',
    allowsWork: false,
    maxDuration: 15,
    requiresReason: false,
    createdBy: 'system',
  },
  {
    id: 'ws-lunch',
    state: 'LUNCH',
    label: 'Lunch',
    description: 'Agent is on a lunch break',
    allowsWork: false,
    maxDuration: 60,
    requiresReason: false,
    createdBy: 'system',
  },
  {
    id: 'ws-training',
    state: 'TRAINING',
    label: 'Training',
    description: 'Agent is in a training session',
    allowsWork: false,
    maxDuration: 120,
    requiresReason: true,
    createdBy: 'system',
  },
  {
    id: 'ws-meeting',
    state: 'MEETING',
    label: 'Meeting',
    description: 'Agent is in a meeting',
    allowsWork: false,
    maxDuration: 60,
    requiresReason: true,
    createdBy: 'system',
  },
];

export const DEFAULT_SKILLS = [
  {
    id: 'skill-customer-service',
    name: 'Customer Service',
    category: 'process',
    description: 'General customer service and support',
    active: true,
  },
  {
    id: 'skill-technical-support',
    name: 'Technical Support',
    category: 'technical',
    description: 'Technical troubleshooting and support',
    active: true,
  },
  {
    id: 'skill-sales',
    name: 'Sales',
    category: 'product',
    description: 'Product sales and upselling',
    active: true,
  },
  {
    id: 'skill-billing',
    name: 'Billing',
    category: 'process',
    description: 'Billing inquiries and adjustments',
    active: true,
  },
  {
    id: 'skill-escalations',
    name: 'Escalations',
    category: 'process',
    description: 'Handling escalated customer issues',
    active: true,
  },
];

export const DEFAULT_USERS = [
  {
    id: 'user-agent1',
    username: 'agent1',
    passwordHash: 'agent1pass',
    displayName: 'Agent One',
    role: 'AGENT',
    email: 'agent1@example.com',
    active: true,
  },
  {
    id: 'user-manager1',
    username: 'manager1',
    passwordHash: 'manager1pass',
    displayName: 'Manager One',
    role: 'MANAGER',
    email: 'manager1@example.com',
    active: true,
  },
  {
    id: 'user-designer1',
    username: 'designer1',
    passwordHash: 'designer1pass',
    displayName: 'Designer One',
    role: 'DESIGNER',
    email: 'designer1@example.com',
    active: true,
  },
  {
    id: 'user-admin1',
    username: 'admin1',
    passwordHash: 'admin1pass',
    displayName: 'Admin One',
    role: 'ADMIN',
    email: 'admin1@example.com',
    active: true,
  },
];
